# Generated by tools/standards_engine/contracts/generate_contract.py.
# Do not edit this file directly.
from __future__ import annotations

import re

from dataclasses import dataclass
from types import MappingProxyType
from typing import Any, ClassVar, Iterator, Literal, Mapping, TypeAlias

INTERFACE_SCHEMA_VERSION = 9
PUBLIC_OPERATIONS = MappingProxyType(
{'inspect': {'capability': 'standards.read',
             'input': 'InspectCall',
             'results': ['InspectionResult', 'RejectedResult']},
 'prepare': {'capability': 'standards.analyze',
             'input': 'PrepareCall',
             'results': ['PendingResult', 'CompleteResult', 'RejectedResult']},
 'query': {'capability': 'standards.read',
           'input': 'QueryCall',
           'results': ['NavigationResult', 'RejectedResult']},
 'resolve': {'capability_by_submission': {'consumer-disposition': 'standards.review.consumer',
                                          'coverage-attestation': 'standards.review.audit',
                                          'impact-disposition': 'standards.review.impact',
                                          'provide-fact': 'standards.analyze'},
             'input': 'ResolveCall',
             'results': ['PendingResult', 'CompleteResult', 'RejectedResult']}}
)
INPUT_DEFINITION_SCHEMAS = MappingProxyType(
{'AnalysisContextHandle': {'additionalProperties': False,
                           'properties': {'context_kind': {'const': 'standards-change'},
                                          'id': {'$ref': '#/$defs/AnalysisContextId'},
                                          'kind': {'const': 'analysis-context-handle'},
                                          'schema_version': {'const': 1}},
                           'required': ['kind', 'id', 'context_kind', 'schema_version'],
                           'type': 'object'},
 'AnalysisContextId': {'pattern': '^standards-change:sha256:[0-9a-f]{64}$',
                       'type': 'string'},
 'AnalysisHandle': {'additionalProperties': False,
                    'properties': {'id': {'$ref': '#/$defs/AnalysisId'},
                                   'kind': {'const': 'analysis-handle'},
                                   'schema_version': {'const': 2}},
                    'required': ['kind', 'id', 'schema_version'],
                    'type': 'object'},
 'AnalysisId': {'pattern': '^analysis:sha256:[0-9a-f]{64}$', 'type': 'string'},
 'AnalysisRequest': {'additionalProperties': False,
                     'properties': {'base_snapshot': {'$ref': '#/$defs/SnapshotHandle'},
                                    'changes': {'items': {'$ref': '#/$defs/ChangeDescriptor'},
                                                'minItems': 1,
                                                'type': 'array'},
                                    'contract_version': {'const': 2},
                                    'kind': {'const': 'analysis-request'},
                                    'prior_analysis': {'$ref': '#/$defs/AnalysisHandle'},
                                    'proposed_snapshot': {'$ref': '#/$defs/SnapshotHandle'},
                                    'semantic_proposals': {'items': {'$ref': '#/$defs/SemanticProposal'},
                                                           'type': 'array',
                                                           'uniqueItems': True}},
                     'required': ['kind',
                                  'base_snapshot',
                                  'proposed_snapshot',
                                  'changes',
                                  'semantic_proposals',
                                  'contract_version'],
                     'type': 'object'},
 'CanonicalId': {'pattern': '^[A-Za-z0-9][A-Za-z0-9._:/-]*$', 'type': 'string'},
 'CertificateHandle': {'additionalProperties': False,
                       'properties': {'id': {'$ref': '#/$defs/CertificateId'},
                                      'kind': {'const': 'certificate-handle'},
                                      'schema_version': {'const': 1}},
                       'required': ['kind', 'id', 'schema_version'],
                       'type': 'object'},
 'CertificateId': {'pattern': '^certificate:sha256:[0-9a-f]{64}$', 'type': 'string'},
 'ChangeDescriptor': {'additionalProperties': False,
                      'properties': {'accepted_ids': {'items': {'$ref': '#/$defs/CanonicalId'},
                                                      'type': 'array',
                                                      'uniqueItems': True},
                                     'accepted_module': {'$ref': '#/$defs/CanonicalId'},
                                     'kind': {'enum': ['modification',
                                                       'addition',
                                                       'removal',
                                                       'move',
                                                       'split',
                                                       'merge']},
                                     'proposed_ids': {'items': {'$ref': '#/$defs/CanonicalId'},
                                                      'type': 'array',
                                                      'uniqueItems': True},
                                     'proposed_module': {'$ref': '#/$defs/CanonicalId'},
                                     'scope': {'$ref': '#/$defs/ReviewScope'}},
                      'required': ['kind', 'accepted_ids', 'proposed_ids', 'scope'],
                      'type': 'object',
                      'x-standards-engine-invariants': {'addition': 'no accepted ID '
                                                                    'and exactly one '
                                                                    'proposed ID',
                                                        'merge': 'at least two '
                                                                 'distinct accepted '
                                                                 'IDs and exactly one '
                                                                 'proposed ID',
                                                        'modification': 'exactly one '
                                                                        'equal '
                                                                        'accepted and '
                                                                        'proposed ID',
                                                        'move': 'exactly one equal '
                                                                'accepted and proposed '
                                                                'ID; module identity '
                                                                'determines '
                                                                'same-module or '
                                                                'cross-module graph '
                                                                'selection',
                                                        'removal': 'exactly one '
                                                                   'accepted ID and no '
                                                                   'proposed ID',
                                                        'split': 'exactly one accepted '
                                                                 'ID and at least two '
                                                                 'distinct proposed '
                                                                 'IDs'}},
 'ConsumerDispositionSubmission': {'additionalProperties': False,
                                   'properties': {'evidence': {'items': {'$ref': '#/$defs/EvidenceReference'},
                                                               'minItems': 1,
                                                               'type': 'array'},
                                                  'fingerprint': {'$ref': '#/$defs/DecisionFingerprint'},
                                                  'kind': {'const': 'consumer-disposition'},
                                                  'obligation_id': {'$ref': '#/$defs/ObligationId'},
                                                  'rationale': {'$ref': '#/$defs/NonEmptyString'},
                                                  'result': {'enum': ['updated',
                                                                      'reviewed-no-change',
                                                                      'not-applicable',
                                                                      'blocked']}},
                                   'required': ['kind',
                                                'obligation_id',
                                                'result',
                                                'rationale',
                                                'evidence',
                                                'fingerprint'],
                                   'type': 'object'},
 'CoverageAttestation': {'additionalProperties': False,
                         'properties': {'auditor_provenance': {'$ref': '#/$defs/NonEmptyString'},
                                        'conclusion': {'const': 'complete'},
                                        'evidence': {'items': {'$ref': '#/$defs/EvidenceReference'},
                                                     'minItems': 1,
                                                     'type': 'array'},
                                        'explicit_exclusions': {'items': {'$ref': '#/$defs/EvidenceReference'},
                                                                'type': 'array'},
                                        'handle': {'$ref': '#/$defs/CoverageAttestationHandle'},
                                        'kind': {'const': 'coverage-attestation'},
                                        'rationale': {'$ref': '#/$defs/NonEmptyString'},
                                        'requirement': {'$ref': '#/$defs/CoverageRequirementHandle'},
                                        'schema_version': {'const': 1}},
                         'required': ['kind',
                                      'handle',
                                      'requirement',
                                      'conclusion',
                                      'evidence',
                                      'explicit_exclusions',
                                      'rationale',
                                      'auditor_provenance',
                                      'schema_version'],
                         'type': 'object',
                         'x-standards-engine-identity': {'domain': 'coding-standards:coverage-attestation:v1',
                                                         'exclude': ['handle'],
                                                         'include': ['requirement',
                                                                     'conclusion',
                                                                     'evidence',
                                                                     'explicit_exclusions',
                                                                     'rationale',
                                                                     'auditor_provenance',
                                                                     'schema_version']}},
 'CoverageAttestationHandle': {'additionalProperties': False,
                               'properties': {'id': {'$ref': '#/$defs/CoverageAttestationId'},
                                              'kind': {'const': 'coverage-attestation-handle'},
                                              'schema_version': {'const': 1}},
                               'required': ['kind', 'id', 'schema_version'],
                               'type': 'object'},
 'CoverageAttestationId': {'pattern': '^coverage-attestation:sha256:[0-9a-f]{64}$',
                           'type': 'string'},
 'CoverageAttestationSubmission': {'additionalProperties': False,
                                   'properties': {'attestation': {'$ref': '#/$defs/CoverageAttestation'},
                                                  'kind': {'const': 'coverage-attestation'},
                                                  'obligation_id': {'$ref': '#/$defs/ObligationId'}},
                                   'required': ['kind', 'obligation_id', 'attestation'],
                                   'type': 'object'},
 'CoverageAuthorityViewHandle': {'additionalProperties': False,
                                 'properties': {'id': {'$ref': '#/$defs/CoverageAuthorityViewId'},
                                                'kind': {'const': 'coverage-authority-view-handle'},
                                                'schema_version': {'const': 1}},
                                 'required': ['kind', 'id', 'schema_version'],
                                 'type': 'object'},
 'CoverageAuthorityViewId': {'pattern': '^coverage-view:sha256:[0-9a-f]{64}$',
                             'type': 'string'},
 'CoverageRequirementHandle': {'additionalProperties': False,
                               'properties': {'id': {'$ref': '#/$defs/CoverageRequirementId'},
                                              'kind': {'const': 'coverage-requirement-handle'},
                                              'schema_version': {'const': 1}},
                               'required': ['kind', 'id', 'schema_version'],
                               'type': 'object'},
 'CoverageRequirementId': {'pattern': '^coverage-requirement:sha256:[0-9a-f]{64}$',
                           'type': 'string'},
 'DecisionDependency': {'additionalProperties': False,
                        'properties': {'class': {'enum': ['policy-unit',
                                                          'semantic-revision',
                                                          'structure',
                                                          'representation',
                                                          'module-locator',
                                                          'applicability-fact',
                                                          'relationship',
                                                          'audit',
                                                          'exception',
                                                          'evidence',
                                                          'provider-contract',
                                                          'applicability-contract',
                                                          'analysis-contract']},
                                       'digest': {'$ref': '#/$defs/Digest'},
                                       'identity': {'$ref': '#/$defs/NonEmptyString'}},
                        'required': ['class', 'identity', 'digest'],
                        'type': 'object'},
 'DecisionFingerprint': {'additionalProperties': False,
                         'properties': {'decision_contract': {'$ref': '#/$defs/CanonicalId'},
                                        'decision_kind': {'$ref': '#/$defs/CanonicalId'},
                                        'dependencies': {'items': {'$ref': '#/$defs/DecisionDependency'},
                                                         'minItems': 1,
                                                         'type': 'array'},
                                        'schema_version': {'const': 1}},
                         'required': ['decision_kind',
                                      'decision_contract',
                                      'schema_version',
                                      'dependencies'],
                         'type': 'object'},
 'Digest': {'pattern': '^sha256:[0-9a-f]{64}$', 'type': 'string'},
 'EdgeId': {'minLength': 1,
            'type': 'string',
            'x-standards-engine-invariants': {'authority': 'value must resolve exactly '
                                                           'through the registered '
                                                           'generic graph; each '
                                                           'registered provider owns '
                                                           'its identity contract and '
                                                           'no lookup inference or '
                                                           'fallback is permitted'}},
 'EvidenceReference': {'additionalProperties': False,
                       'properties': {'digest': {'$ref': '#/$defs/Digest'},
                                      'id': {'$ref': '#/$defs/CanonicalId'},
                                      'provider_contract': {'$ref': '#/$defs/CanonicalId'},
                                      'provider_contract_version': {'$ref': '#/$defs/NonEmptyString'}},
                       'required': ['id',
                                    'digest',
                                    'provider_contract',
                                    'provider_contract_version'],
                       'type': 'object'},
 'FactObservationHandle': {'additionalProperties': False,
                           'properties': {'id': {'$ref': '#/$defs/FactObservationId'},
                                          'kind': {'const': 'fact-observation-handle'},
                                          'schema_version': {'const': 1}},
                           'required': ['kind', 'id', 'schema_version'],
                           'type': 'object'},
 'FactObservationId': {'pattern': '^fact-observation:sha256:[0-9a-f]{64}$',
                       'type': 'string'},
 'FactRequirementHandle': {'additionalProperties': False,
                           'properties': {'id': {'$ref': '#/$defs/FactRequirementId'},
                                          'kind': {'const': 'fact-requirement-handle'},
                                          'schema_version': {'const': 1}},
                           'required': ['kind', 'id', 'schema_version'],
                           'type': 'object'},
 'FactRequirementId': {'pattern': '^fact-requirement:sha256:[0-9a-f]{64}$',
                       'type': 'string'},
 'FactSet': {'additionalProperties': {'$ref': '#/$defs/FactValue'}, 'type': 'object'},
 'FactValue': {'oneOf': [{'additionalProperties': False,
                          'properties': {'state': {'const': 'known'},
                                         'type': {'const': 'boolean'},
                                         'value': {'type': 'boolean'}},
                          'required': ['type', 'state', 'value'],
                          'type': 'object'},
                         {'additionalProperties': False,
                          'properties': {'state': {'const': 'known'},
                                         'type': {'enum': ['boolean',
                                                           'enum',
                                                           'string',
                                                           'string-set',
                                                           'enum-set',
                                                           'canonical-id']},
                                         'value': {'type': 'null'}},
                          'required': ['type', 'state', 'value'],
                          'type': 'object'},
                         {'additionalProperties': False,
                          'properties': {'state': {'const': 'known'},
                                         'type': {'enum': ['enum',
                                                           'string',
                                                           'canonical-id']},
                                         'value': {'type': 'string'}},
                          'required': ['type', 'state', 'value'],
                          'type': 'object'},
                         {'additionalProperties': False,
                          'properties': {'state': {'const': 'known'},
                                         'type': {'enum': ['string-set', 'enum-set']},
                                         'value': {'items': {'type': 'string'},
                                                   'type': 'array',
                                                   'uniqueItems': True}},
                          'required': ['type', 'state', 'value'],
                          'type': 'object'},
                         {'additionalProperties': False,
                          'properties': {'state': {'enum': ['known-absent', 'unknown']},
                                         'type': {'enum': ['boolean',
                                                           'enum',
                                                           'string',
                                                           'string-set',
                                                           'enum-set',
                                                           'canonical-id']}},
                          'required': ['type', 'state'],
                          'type': 'object'}]},
 'ImpactDispositionSubmission': {'additionalProperties': False,
                                 'properties': {'evidence': {'items': {'$ref': '#/$defs/EvidenceReference'},
                                                             'minItems': 1,
                                                             'type': 'array'},
                                                'fingerprint': {'$ref': '#/$defs/DecisionFingerprint'},
                                                'kind': {'const': 'impact-disposition'},
                                                'obligation_id': {'$ref': '#/$defs/ObligationId'},
                                                'rationale': {'$ref': '#/$defs/NonEmptyString'},
                                                'result': {'enum': ['confirmed',
                                                                    'resolved-no-impact',
                                                                    'requires-change',
                                                                    'blocked']}},
                                 'required': ['kind',
                                              'obligation_id',
                                              'result',
                                              'rationale',
                                              'evidence',
                                              'fingerprint'],
                                 'type': 'object'},
 'InspectCall': {'additionalProperties': False,
                 'properties': {'handle': {'$ref': '#/$defs/InspectableHandle'}},
                 'required': ['handle'],
                 'type': 'object'},
 'InspectableHandle': {'oneOf': [{'$ref': '#/$defs/SnapshotHandle'},
                                 {'$ref': '#/$defs/NavigationHandle'},
                                 {'$ref': '#/$defs/AnalysisHandle'},
                                 {'$ref': '#/$defs/PolicyHandle'},
                                 {'$ref': '#/$defs/RelationshipHandle'},
                                 {'$ref': '#/$defs/CertificateHandle'},
                                 {'$ref': '#/$defs/CoverageAuthorityViewHandle'},
                                 {'$ref': '#/$defs/CoverageRequirementHandle'},
                                 {'$ref': '#/$defs/CoverageAttestationHandle'},
                                 {'$ref': '#/$defs/AnalysisContextHandle'},
                                 {'$ref': '#/$defs/FactRequirementHandle'},
                                 {'$ref': '#/$defs/FactObservationHandle'}]},
 'NavigationHandle': {'additionalProperties': False,
                      'properties': {'id': {'$ref': '#/$defs/NavigationId'},
                                     'kind': {'const': 'navigation-handle'},
                                     'schema_version': {'const': 2},
                                     'snapshot': {'$ref': '#/$defs/SnapshotHandle'}},
                      'required': ['kind', 'id', 'snapshot', 'schema_version'],
                      'type': 'object'},
 'NavigationId': {'pattern': '^navigation:sha256:[0-9a-f]{64}$', 'type': 'string'},
 'NonEmptyString': {'minLength': 1, 'type': 'string'},
 'ObligationId': {'pattern': '^obligation:sha256:[0-9a-f]{64}$', 'type': 'string'},
 'PolicyHandle': {'additionalProperties': False,
                  'properties': {'id': {'$ref': '#/$defs/CanonicalId'},
                                 'kind': {'const': 'policy-handle'},
                                 'snapshot': {'$ref': '#/$defs/SnapshotHandle'}},
                  'required': ['kind', 'id', 'snapshot'],
                  'type': 'object'},
 'PrepareCall': {'additionalProperties': False,
                 'properties': {'request': {'$ref': '#/$defs/AnalysisRequest'}},
                 'required': ['request'],
                 'type': 'object'},
 'ProvideFactSubmission': {'additionalProperties': False,
                           'properties': {'evidence': {'items': {'$ref': '#/$defs/EvidenceReference'},
                                                       'minItems': 1,
                                                       'type': 'array',
                                                       'uniqueItems': True},
                                          'kind': {'const': 'provide-fact'},
                                          'requirement': {'$ref': '#/$defs/FactRequirementHandle'},
                                          'value': {'$ref': '#/$defs/FactValue'}},
                           'required': ['kind', 'requirement', 'value', 'evidence'],
                           'type': 'object'},
 'QueryCall': {'additionalProperties': False,
               'properties': {'request': {'$ref': '#/$defs/QueryRequest'},
                              'snapshot': {'$ref': '#/$defs/SnapshotHandle'}},
               'required': ['snapshot', 'request'],
               'type': 'object'},
 'QueryRequest': {'oneOf': [{'$ref': '#/$defs/RouteRequest'},
                            {'$ref': '#/$defs/ReadRequest'},
                            {'$ref': '#/$defs/RelatedRequest'}]},
 'ReadRequest': {'additionalProperties': False,
                 'properties': {'kind': {'const': 'read'},
                                'target': {'$ref': '#/$defs/CanonicalId'}},
                 'required': ['kind', 'target'],
                 'type': 'object'},
 'RelatedRequest': {'additionalProperties': False,
                    'properties': {'direction': {'enum': ['incoming',
                                                          'outgoing',
                                                          'both']},
                                   'groups': {'items': {'$ref': '#/$defs/CanonicalId'},
                                              'minItems': 1,
                                              'type': 'array',
                                              'uniqueItems': True},
                                   'kind': {'const': 'related'},
                                   'target': {'$ref': '#/$defs/CanonicalId'},
                                   'transitive': {'default': False, 'type': 'boolean'}},
                    'required': ['kind', 'target', 'groups', 'direction', 'transitive'],
                    'type': 'object'},
 'RelationshipHandle': {'additionalProperties': False,
                        'properties': {'id': {'$ref': '#/$defs/EdgeId'},
                                       'kind': {'const': 'relationship-handle'},
                                       'snapshot': {'$ref': '#/$defs/SnapshotHandle'}},
                        'required': ['kind', 'id', 'snapshot'],
                        'type': 'object'},
 'ResolveCall': {'additionalProperties': False,
                 'properties': {'analysis': {'$ref': '#/$defs/AnalysisHandle'},
                                'submission': {'$ref': '#/$defs/Submission'}},
                 'required': ['analysis', 'submission'],
                 'type': 'object'},
 'ReviewScope': {'oneOf': [{'$ref': '#/$defs/StructuredScope'},
                           {'$ref': '#/$defs/WholeArtifactScope'}]},
 'RouteRequest': {'additionalProperties': False,
                  'properties': {'facts': {'$ref': '#/$defs/FactSet'},
                                 'kind': {'const': 'route'}},
                  'required': ['kind', 'facts'],
                  'type': 'object'},
 'SemanticProposal': {'additionalProperties': False,
                      'properties': {'accepted_semantic_revision': {'oneOf': [{'minimum': 1,
                                                                               'type': 'integer'},
                                                                              {'type': 'null'}]},
                                     'intent': {'$ref': '#/$defs/NonEmptyString'},
                                     'policy': {'$ref': '#/$defs/CanonicalId'},
                                     'proposed_semantic_revision': {'minimum': 1,
                                                                    'type': 'integer'},
                                     'structural_digest': {'$ref': '#/$defs/Digest'}},
                      'required': ['policy',
                                   'accepted_semantic_revision',
                                   'proposed_semantic_revision',
                                   'intent',
                                   'structural_digest'],
                      'type': 'object'},
 'SnapshotHandle': {'additionalProperties': False,
                    'properties': {'id': {'$ref': '#/$defs/SnapshotId'},
                                   'kind': {'const': 'snapshot-handle'},
                                   'schema_version': {'const': 2}},
                    'required': ['kind', 'id', 'schema_version'],
                    'type': 'object'},
 'SnapshotId': {'pattern': '^snapshot:sha256:[0-9a-f]{64}$', 'type': 'string'},
 'StructuredScope': {'additionalProperties': False,
                     'properties': {'heading_path': {'items': {'$ref': '#/$defs/NonEmptyString'},
                                                     'minItems': 1,
                                                     'type': 'array'},
                                    'kind': {'const': 'structured'}},
                     'required': ['kind', 'heading_path'],
                     'type': 'object'},
 'Submission': {'oneOf': [{'$ref': '#/$defs/ProvideFactSubmission'},
                          {'$ref': '#/$defs/ConsumerDispositionSubmission'},
                          {'$ref': '#/$defs/ImpactDispositionSubmission'},
                          {'$ref': '#/$defs/CoverageAttestationSubmission'}]},
 'WholeArtifactScope': {'additionalProperties': False,
                        'properties': {'kind': {'const': 'whole-artifact'}},
                        'required': ['kind'],
                        'type': 'object'}}
)
INPUT_FIELD_NAMES = MappingProxyType(
{'AnalysisContextHandle': {'context_kind': 'context_kind',
                           'id': 'id',
                           'kind': 'kind',
                           'schema_version': 'schema_version'},
 'AnalysisHandle': {'id': 'id', 'kind': 'kind', 'schema_version': 'schema_version'},
 'AnalysisRequest': {'base_snapshot': 'base_snapshot',
                     'changes': 'changes',
                     'contract_version': 'contract_version',
                     'kind': 'kind',
                     'prior_analysis': 'prior_analysis',
                     'proposed_snapshot': 'proposed_snapshot',
                     'semantic_proposals': 'semantic_proposals'},
 'CertificateHandle': {'id': 'id', 'kind': 'kind', 'schema_version': 'schema_version'},
 'ChangeDescriptor': {'accepted_ids': 'accepted_ids',
                      'accepted_module': 'accepted_module',
                      'kind': 'kind',
                      'proposed_ids': 'proposed_ids',
                      'proposed_module': 'proposed_module',
                      'scope': 'scope'},
 'ConsumerDispositionSubmission': {'evidence': 'evidence',
                                   'fingerprint': 'fingerprint',
                                   'kind': 'kind',
                                   'obligation_id': 'obligation_id',
                                   'rationale': 'rationale',
                                   'result': 'result'},
 'CoverageAttestation': {'auditor_provenance': 'auditor_provenance',
                         'conclusion': 'conclusion',
                         'evidence': 'evidence',
                         'explicit_exclusions': 'explicit_exclusions',
                         'handle': 'handle',
                         'kind': 'kind',
                         'rationale': 'rationale',
                         'requirement': 'requirement',
                         'schema_version': 'schema_version'},
 'CoverageAttestationHandle': {'id': 'id',
                               'kind': 'kind',
                               'schema_version': 'schema_version'},
 'CoverageAttestationSubmission': {'attestation': 'attestation',
                                   'kind': 'kind',
                                   'obligation_id': 'obligation_id'},
 'CoverageAuthorityViewHandle': {'id': 'id',
                                 'kind': 'kind',
                                 'schema_version': 'schema_version'},
 'CoverageRequirementHandle': {'id': 'id',
                               'kind': 'kind',
                               'schema_version': 'schema_version'},
 'DecisionDependency': {'class': 'class_', 'digest': 'digest', 'identity': 'identity'},
 'DecisionFingerprint': {'decision_contract': 'decision_contract',
                         'decision_kind': 'decision_kind',
                         'dependencies': 'dependencies',
                         'schema_version': 'schema_version'},
 'EvidenceReference': {'digest': 'digest',
                       'id': 'id',
                       'provider_contract': 'provider_contract',
                       'provider_contract_version': 'provider_contract_version'},
 'FactObservationHandle': {'id': 'id',
                           'kind': 'kind',
                           'schema_version': 'schema_version'},
 'FactRequirementHandle': {'id': 'id',
                           'kind': 'kind',
                           'schema_version': 'schema_version'},
 'ImpactDispositionSubmission': {'evidence': 'evidence',
                                 'fingerprint': 'fingerprint',
                                 'kind': 'kind',
                                 'obligation_id': 'obligation_id',
                                 'rationale': 'rationale',
                                 'result': 'result'},
 'InspectCall': {'handle': 'handle'},
 'NavigationHandle': {'id': 'id',
                      'kind': 'kind',
                      'schema_version': 'schema_version',
                      'snapshot': 'snapshot'},
 'PolicyHandle': {'id': 'id', 'kind': 'kind', 'snapshot': 'snapshot'},
 'PrepareCall': {'request': 'request'},
 'ProvideFactSubmission': {'evidence': 'evidence',
                           'kind': 'kind',
                           'requirement': 'requirement',
                           'value': 'value'},
 'QueryCall': {'request': 'request', 'snapshot': 'snapshot'},
 'ReadRequest': {'kind': 'kind', 'target': 'target'},
 'RelatedRequest': {'direction': 'direction',
                    'groups': 'groups',
                    'kind': 'kind',
                    'target': 'target',
                    'transitive': 'transitive'},
 'RelationshipHandle': {'id': 'id', 'kind': 'kind', 'snapshot': 'snapshot'},
 'ResolveCall': {'analysis': 'analysis', 'submission': 'submission'},
 'RouteRequest': {'facts': 'facts', 'kind': 'kind'},
 'SemanticProposal': {'accepted_semantic_revision': 'accepted_semantic_revision',
                      'intent': 'intent',
                      'policy': 'policy',
                      'proposed_semantic_revision': 'proposed_semantic_revision',
                      'structural_digest': 'structural_digest'},
 'SnapshotHandle': {'id': 'id', 'kind': 'kind', 'schema_version': 'schema_version'},
 'StructuredScope': {'heading_path': 'heading_path', 'kind': 'kind'},
 'WholeArtifactScope': {'kind': 'kind'}}
)
RESULT_KIND_TO_DEFINITION = MappingProxyType(
{'analysis-context-inspection-result': 'AnalysisContextInspectionResult',
 'analysis-state': 'AnalysisState',
 'certificate-inspection-result': 'CertificateInspectionResult',
 'complete-result': 'CompleteResult',
 'coverage-attestation-inspection-result': 'CoverageAttestationInspectionResult',
 'coverage-authority-view-inspection-result': 'CoverageAuthorityViewInspectionResult',
 'coverage-requirement-inspection-result': 'CoverageRequirementInspectionResult',
 'fact-observation-inspection-result': 'FactObservationInspectionResult',
 'fact-requirement-inspection-result': 'FactRequirementInspectionResult',
 'navigation-inspection-result': 'NavigationInspectionResult',
 'pending-result': 'PendingResult',
 'policy-inspection-result': 'PolicyInspectionResult',
 'read-result': 'ReadResult',
 'rejected-result': 'RejectedResult',
 'related-result': 'RelatedResult',
 'relationship-inspection-result': 'RelationshipInspectionResult',
 'route-result': 'RouteResult',
 'snapshot-inspection-result': 'SnapshotInspectionResult'}
)
INSPECTABLE_HANDLE_DEFINITIONS = ('SnapshotHandle', 'NavigationHandle', 'AnalysisHandle', 'PolicyHandle', 'RelationshipHandle', 'CertificateHandle', 'CoverageAuthorityViewHandle', 'CoverageRequirementHandle', 'CoverageAttestationHandle', 'AnalysisContextHandle', 'FactRequirementHandle', 'FactObservationHandle')


def _freeze(value: Any) -> Any:
    if isinstance(value, Mapping):
        return MappingProxyType({str(key): _freeze(item) for key, item in value.items()})
    if isinstance(value, (list, tuple)):
        return tuple(_freeze(item) for item in value)
    return value


def _thaw(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {key: _thaw(item) for key, item in value.items()}
    if isinstance(value, tuple):
        return [_thaw(item) for item in value]
    return value


class ContractObject(Mapping[str, object]):
    __definition__: ClassVar[str]

    @classmethod
    def from_value(cls, value: Mapping[str, object]):
        selected = decode_contract(cls.__definition__, value)
        if not isinstance(selected, cls):
            raise TypeError(f"{cls.__definition__} decoded to the wrong type")
        return selected

    def as_contract(self) -> dict[str, object]:
        required = set(INPUT_DEFINITION_SCHEMAS[self.__definition__].get("required", ()))
        result = {}
        for contract_name, python_name in INPUT_FIELD_NAMES[self.__definition__].items():
            value = getattr(self, python_name)
            if value is None and contract_name not in required:
                continue
            result[contract_name] = _encode(value)
        return result

    def __getitem__(self, key: str) -> object:
        return self.as_contract()[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self.as_contract())

    def __len__(self) -> int:
        return len(self.as_contract())


def _encode(value: object) -> object:
    if isinstance(value, ContractObject):
        return value.as_contract()
    if isinstance(value, Mapping):
        return {str(key): _encode(item) for key, item in value.items()}
    if isinstance(value, tuple):
        return [_encode(item) for item in value]
    return value


def _decode_node(node: Mapping[str, object], value: object) -> object:
    reference = node.get("$ref")
    if isinstance(reference, str):
        return decode_contract(reference.rsplit("/", 1)[1], value)
    variants = node.get("oneOf")
    if isinstance(variants, list):
        failures = []
        for variant in variants:
            try:
                return _decode_node(variant, value)
            except (TypeError, ValueError) as error:
                failures.append(str(error))
        raise TypeError("value matches no generated union variant: " + "; ".join(failures))
    if "const" in node and _encode(value) != node["const"]:
        raise ValueError(f"expected constant {node['const']!r}")
    if "enum" in node and value not in node["enum"]:
        raise ValueError(f"value {value!r} is outside the generated enum")
    value_type = node.get("type")
    if value_type == "string" and not isinstance(value, str):
        raise TypeError("expected string")
    if value_type == "string" and len(value) < int(node.get("minLength", 0)):
        raise ValueError("string is shorter than the generated minimum")
    if value_type == "string" and "pattern" in node and re.fullmatch(node["pattern"], value) is None:
        raise ValueError("string does not match the generated pattern")
    if value_type == "integer" and (not isinstance(value, int) or isinstance(value, bool)):
        raise TypeError("expected integer")
    if value_type == "boolean" and not isinstance(value, bool):
        raise TypeError("expected boolean")
    if value_type == "null" and value is not None:
        raise TypeError("expected null")
    if value_type == "array":
        if not isinstance(value, (list, tuple)):
            raise TypeError("expected array")
        result = tuple(_decode_node(node.get("items", {}), item) for item in value)
        if len(result) < int(node.get("minItems", 0)):
            raise ValueError("array is shorter than the generated minimum")
        if node.get("uniqueItems") and any(item in result[:index] for index, item in enumerate(result)):
            raise ValueError("array items must be unique")
        return result
    if value_type == "object":
        if isinstance(value, ContractObject) or hasattr(value, "as_contract"):
            value = value.as_contract()
        if not isinstance(value, Mapping):
            raise TypeError("expected object")
        additional = node.get("additionalProperties")
        if isinstance(additional, Mapping):
            return MappingProxyType({str(key): _decode_node(additional, item) for key, item in value.items()})
        return _freeze(value)
    return value


def decode_contract(definition: str, value: object) -> object:
    node = INPUT_DEFINITION_SCHEMAS.get(definition)
    if node is None:
        raise ValueError(f"unknown generated input definition {definition!r}")
    selected = _CLASS_BY_DEFINITION.get(definition)
    if selected is None:
        return _decode_node(node, value)
    if isinstance(value, selected):
        return value
    if hasattr(value, "as_contract"):
        value = value.as_contract()
    if not isinstance(value, Mapping):
        raise TypeError(f"{definition} must be an object")
    required = set(node.get("required", ()))
    properties = node.get("properties", {})
    missing = required - set(value)
    extra = set(value) - set(properties)
    if missing:
        raise ValueError(f"{definition} is missing {sorted(missing)!r}")
    if extra:
        raise ValueError(f"{definition} has unexpected fields {sorted(extra)!r}")
    arguments = {}
    for contract_name, python_name in INPUT_FIELD_NAMES[definition].items():
        if contract_name in value:
            arguments[python_name] = _decode_node(properties[contract_name], value[contract_name])
    return selected(**arguments)


def _coerce_object(value: ContractObject) -> None:
    node = INPUT_DEFINITION_SCHEMAS[value.__definition__]
    required = set(node.get("required", ()))
    for contract_name, python_name in INPUT_FIELD_NAMES[value.__definition__].items():
        selected = getattr(value, python_name)
        if selected is None and contract_name not in required:
            continue
        object.__setattr__(value, python_name, _decode_node(node["properties"][contract_name], selected))


@dataclass(frozen=True, slots=True)
class AnalysisContextHandle(ContractObject):
    __definition__: ClassVar[str] = 'AnalysisContextHandle'
    id: AnalysisContextId
    context_kind: Literal['standards-change'] = 'standards-change'
    schema_version: Literal[1] = 1
    kind: Literal['analysis-context-handle'] = 'analysis-context-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class AnalysisHandle(ContractObject):
    __definition__: ClassVar[str] = 'AnalysisHandle'
    id: AnalysisId
    schema_version: Literal[2] = 2
    kind: Literal['analysis-handle'] = 'analysis-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class AnalysisRequest(ContractObject):
    __definition__: ClassVar[str] = 'AnalysisRequest'
    base_snapshot: SnapshotHandle
    proposed_snapshot: SnapshotHandle
    changes: tuple[ChangeDescriptor, ...]
    semantic_proposals: tuple[SemanticProposal, ...]
    prior_analysis: AnalysisHandle | None = None
    contract_version: Literal[2] = 2
    kind: Literal['analysis-request'] = 'analysis-request'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class CertificateHandle(ContractObject):
    __definition__: ClassVar[str] = 'CertificateHandle'
    id: CertificateId
    schema_version: Literal[1] = 1
    kind: Literal['certificate-handle'] = 'certificate-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class ChangeDescriptor(ContractObject):
    __definition__: ClassVar[str] = 'ChangeDescriptor'
    kind: Literal['modification', 'addition', 'removal', 'move', 'split', 'merge']
    accepted_ids: tuple[CanonicalId, ...]
    proposed_ids: tuple[CanonicalId, ...]
    scope: ReviewScope
    accepted_module: CanonicalId | None = None
    proposed_module: CanonicalId | None = None

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class ConsumerDispositionSubmission(ContractObject):
    __definition__: ClassVar[str] = 'ConsumerDispositionSubmission'
    obligation_id: ObligationId
    result: Literal['updated', 'reviewed-no-change', 'not-applicable', 'blocked']
    rationale: NonEmptyString
    evidence: tuple[EvidenceReference, ...]
    fingerprint: DecisionFingerprint
    kind: Literal['consumer-disposition'] = 'consumer-disposition'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class CoverageAttestation(ContractObject):
    __definition__: ClassVar[str] = 'CoverageAttestation'
    handle: CoverageAttestationHandle
    requirement: CoverageRequirementHandle
    evidence: tuple[EvidenceReference, ...]
    explicit_exclusions: tuple[EvidenceReference, ...]
    rationale: NonEmptyString
    auditor_provenance: NonEmptyString
    conclusion: Literal['complete'] = 'complete'
    schema_version: Literal[1] = 1
    kind: Literal['coverage-attestation'] = 'coverage-attestation'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class CoverageAttestationHandle(ContractObject):
    __definition__: ClassVar[str] = 'CoverageAttestationHandle'
    id: CoverageAttestationId
    schema_version: Literal[1] = 1
    kind: Literal['coverage-attestation-handle'] = 'coverage-attestation-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class CoverageAttestationSubmission(ContractObject):
    __definition__: ClassVar[str] = 'CoverageAttestationSubmission'
    obligation_id: ObligationId
    attestation: CoverageAttestation
    kind: Literal['coverage-attestation'] = 'coverage-attestation'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class CoverageAuthorityViewHandle(ContractObject):
    __definition__: ClassVar[str] = 'CoverageAuthorityViewHandle'
    id: CoverageAuthorityViewId
    schema_version: Literal[1] = 1
    kind: Literal['coverage-authority-view-handle'] = 'coverage-authority-view-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class CoverageRequirementHandle(ContractObject):
    __definition__: ClassVar[str] = 'CoverageRequirementHandle'
    id: CoverageRequirementId
    schema_version: Literal[1] = 1
    kind: Literal['coverage-requirement-handle'] = 'coverage-requirement-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class DecisionDependency(ContractObject):
    __definition__: ClassVar[str] = 'DecisionDependency'
    class_: Literal['policy-unit', 'semantic-revision', 'structure', 'representation', 'module-locator', 'applicability-fact', 'relationship', 'audit', 'exception', 'evidence', 'provider-contract', 'applicability-contract', 'analysis-contract']
    identity: NonEmptyString
    digest: Digest

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class DecisionFingerprint(ContractObject):
    __definition__: ClassVar[str] = 'DecisionFingerprint'
    decision_kind: CanonicalId
    decision_contract: CanonicalId
    dependencies: tuple[DecisionDependency, ...]
    schema_version: Literal[1] = 1

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class EvidenceReference(ContractObject):
    __definition__: ClassVar[str] = 'EvidenceReference'
    id: CanonicalId
    digest: Digest
    provider_contract: CanonicalId
    provider_contract_version: NonEmptyString

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class FactObservationHandle(ContractObject):
    __definition__: ClassVar[str] = 'FactObservationHandle'
    id: FactObservationId
    schema_version: Literal[1] = 1
    kind: Literal['fact-observation-handle'] = 'fact-observation-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class FactRequirementHandle(ContractObject):
    __definition__: ClassVar[str] = 'FactRequirementHandle'
    id: FactRequirementId
    schema_version: Literal[1] = 1
    kind: Literal['fact-requirement-handle'] = 'fact-requirement-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class ImpactDispositionSubmission(ContractObject):
    __definition__: ClassVar[str] = 'ImpactDispositionSubmission'
    obligation_id: ObligationId
    result: Literal['confirmed', 'resolved-no-impact', 'requires-change', 'blocked']
    rationale: NonEmptyString
    evidence: tuple[EvidenceReference, ...]
    fingerprint: DecisionFingerprint
    kind: Literal['impact-disposition'] = 'impact-disposition'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class InspectCall(ContractObject):
    __definition__: ClassVar[str] = 'InspectCall'
    handle: InspectableHandle

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class NavigationHandle(ContractObject):
    __definition__: ClassVar[str] = 'NavigationHandle'
    id: NavigationId
    snapshot: SnapshotHandle
    schema_version: Literal[2] = 2
    kind: Literal['navigation-handle'] = 'navigation-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class PolicyHandle(ContractObject):
    __definition__: ClassVar[str] = 'PolicyHandle'
    id: CanonicalId
    snapshot: SnapshotHandle
    kind: Literal['policy-handle'] = 'policy-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class PrepareCall(ContractObject):
    __definition__: ClassVar[str] = 'PrepareCall'
    request: AnalysisRequest

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class ProvideFactSubmission(ContractObject):
    __definition__: ClassVar[str] = 'ProvideFactSubmission'
    requirement: FactRequirementHandle
    value: FactValue
    evidence: tuple[EvidenceReference, ...]
    kind: Literal['provide-fact'] = 'provide-fact'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class QueryCall(ContractObject):
    __definition__: ClassVar[str] = 'QueryCall'
    snapshot: SnapshotHandle
    request: QueryRequest

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class ReadRequest(ContractObject):
    __definition__: ClassVar[str] = 'ReadRequest'
    target: CanonicalId
    kind: Literal['read'] = 'read'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class RelatedRequest(ContractObject):
    __definition__: ClassVar[str] = 'RelatedRequest'
    target: CanonicalId
    groups: tuple[CanonicalId, ...]
    direction: Literal['incoming', 'outgoing', 'both']
    transitive: bool = False
    kind: Literal['related'] = 'related'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class RelationshipHandle(ContractObject):
    __definition__: ClassVar[str] = 'RelationshipHandle'
    id: EdgeId
    snapshot: SnapshotHandle
    kind: Literal['relationship-handle'] = 'relationship-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class ResolveCall(ContractObject):
    __definition__: ClassVar[str] = 'ResolveCall'
    analysis: AnalysisHandle
    submission: Submission

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class RouteRequest(ContractObject):
    __definition__: ClassVar[str] = 'RouteRequest'
    facts: FactSet
    kind: Literal['route'] = 'route'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class SemanticProposal(ContractObject):
    __definition__: ClassVar[str] = 'SemanticProposal'
    policy: CanonicalId
    accepted_semantic_revision: int | None
    proposed_semantic_revision: int
    intent: NonEmptyString
    structural_digest: Digest

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class SnapshotHandle(ContractObject):
    __definition__: ClassVar[str] = 'SnapshotHandle'
    id: SnapshotId
    schema_version: Literal[2] = 2
    kind: Literal['snapshot-handle'] = 'snapshot-handle'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class StructuredScope(ContractObject):
    __definition__: ClassVar[str] = 'StructuredScope'
    heading_path: tuple[NonEmptyString, ...]
    kind: Literal['structured'] = 'structured'

    def __post_init__(self) -> None:
        _coerce_object(self)


@dataclass(frozen=True, slots=True)
class WholeArtifactScope(ContractObject):
    __definition__: ClassVar[str] = 'WholeArtifactScope'
    kind: Literal['whole-artifact'] = 'whole-artifact'

    def __post_init__(self) -> None:
        _coerce_object(self)


_CLASS_BY_DEFINITION = MappingProxyType({
    'AnalysisContextHandle': AnalysisContextHandle,
    'AnalysisHandle': AnalysisHandle,
    'AnalysisRequest': AnalysisRequest,
    'CertificateHandle': CertificateHandle,
    'ChangeDescriptor': ChangeDescriptor,
    'ConsumerDispositionSubmission': ConsumerDispositionSubmission,
    'CoverageAttestation': CoverageAttestation,
    'CoverageAttestationHandle': CoverageAttestationHandle,
    'CoverageAttestationSubmission': CoverageAttestationSubmission,
    'CoverageAuthorityViewHandle': CoverageAuthorityViewHandle,
    'CoverageRequirementHandle': CoverageRequirementHandle,
    'DecisionDependency': DecisionDependency,
    'DecisionFingerprint': DecisionFingerprint,
    'EvidenceReference': EvidenceReference,
    'FactObservationHandle': FactObservationHandle,
    'FactRequirementHandle': FactRequirementHandle,
    'ImpactDispositionSubmission': ImpactDispositionSubmission,
    'InspectCall': InspectCall,
    'NavigationHandle': NavigationHandle,
    'PolicyHandle': PolicyHandle,
    'PrepareCall': PrepareCall,
    'ProvideFactSubmission': ProvideFactSubmission,
    'QueryCall': QueryCall,
    'ReadRequest': ReadRequest,
    'RelatedRequest': RelatedRequest,
    'RelationshipHandle': RelationshipHandle,
    'ResolveCall': ResolveCall,
    'RouteRequest': RouteRequest,
    'SemanticProposal': SemanticProposal,
    'SnapshotHandle': SnapshotHandle,
    'StructuredScope': StructuredScope,
    'WholeArtifactScope': WholeArtifactScope,
})


AnalysisContextId: TypeAlias = str
AnalysisId: TypeAlias = str
CanonicalId: TypeAlias = str
CertificateId: TypeAlias = str
CoverageAttestationId: TypeAlias = str
CoverageAuthorityViewId: TypeAlias = str
CoverageRequirementId: TypeAlias = str
Digest: TypeAlias = str
EdgeId: TypeAlias = str
FactObservationId: TypeAlias = str
FactRequirementId: TypeAlias = str
FactValue: TypeAlias = Mapping[str, object]
FactSet: TypeAlias = Mapping[str, FactValue]
InspectableHandle: TypeAlias = SnapshotHandle | NavigationHandle | AnalysisHandle | PolicyHandle | RelationshipHandle | CertificateHandle | CoverageAuthorityViewHandle | CoverageRequirementHandle | CoverageAttestationHandle | AnalysisContextHandle | FactRequirementHandle | FactObservationHandle
NavigationId: TypeAlias = str
NonEmptyString: TypeAlias = str
ObligationId: TypeAlias = str
QueryRequest: TypeAlias = RouteRequest | ReadRequest | RelatedRequest
ReviewScope: TypeAlias = StructuredScope | WholeArtifactScope
SnapshotId: TypeAlias = str
Submission: TypeAlias = ProvideFactSubmission | ConsumerDispositionSubmission | ImpactDispositionSubmission | CoverageAttestationSubmission


@dataclass(frozen=True, slots=True)
class ContractResult:
    _value: Mapping[str, object]

    @classmethod
    def from_value(cls, value: dict[str, object]):
        return cls(_freeze(value))

    @property
    def kind(self) -> str:
        return str(self._value['kind'])

    def as_contract(self) -> dict[str, object]:
        return _thaw(self._value)


class RouteResult(ContractResult):
    pass

class ReadResult(ContractResult):
    pass

class RelatedResult(ContractResult):
    pass

class PendingResult(ContractResult):
    pass

class CompleteResult(ContractResult):
    pass

class RejectedResult(ContractResult):
    pass

class SnapshotInspectionResult(ContractResult):
    pass

class PolicyInspectionResult(ContractResult):
    pass

class RelationshipInspectionResult(ContractResult):
    pass

class NavigationInspectionResult(ContractResult):
    pass

class CertificateInspectionResult(ContractResult):
    pass

class CoverageAuthorityViewInspectionResult(ContractResult):
    pass

class CoverageRequirementInspectionResult(ContractResult):
    pass

class CoverageAttestationInspectionResult(ContractResult):
    pass

class AnalysisContextInspectionResult(ContractResult):
    pass

class FactRequirementInspectionResult(ContractResult):
    pass

class FactObservationInspectionResult(ContractResult):
    pass


QueryResult: TypeAlias = RouteResult | ReadResult | RelatedResult | RejectedResult
ContractInspectionResult: TypeAlias = SnapshotInspectionResult | PolicyInspectionResult | RelationshipInspectionResult | NavigationInspectionResult | CertificateInspectionResult | CoverageAuthorityViewInspectionResult | CoverageRequirementInspectionResult | CoverageAttestationInspectionResult | AnalysisContextInspectionResult | FactRequirementInspectionResult | FactObservationInspectionResult | RejectedResult

__all__ = (
    'AnalysisContextHandle',
    'AnalysisContextId',
    'AnalysisContextInspectionResult',
    'AnalysisHandle',
    'AnalysisId',
    'AnalysisRequest',
    'CanonicalId',
    'CertificateHandle',
    'CertificateId',
    'CertificateInspectionResult',
    'ChangeDescriptor',
    'CompleteResult',
    'ConsumerDispositionSubmission',
    'ContractInspectionResult',
    'ContractObject',
    'ContractResult',
    'CoverageAttestation',
    'CoverageAttestationHandle',
    'CoverageAttestationId',
    'CoverageAttestationInspectionResult',
    'CoverageAttestationSubmission',
    'CoverageAuthorityViewHandle',
    'CoverageAuthorityViewId',
    'CoverageAuthorityViewInspectionResult',
    'CoverageRequirementHandle',
    'CoverageRequirementId',
    'CoverageRequirementInspectionResult',
    'DecisionDependency',
    'DecisionFingerprint',
    'Digest',
    'EdgeId',
    'EvidenceReference',
    'FactObservationHandle',
    'FactObservationId',
    'FactObservationInspectionResult',
    'FactRequirementHandle',
    'FactRequirementId',
    'FactRequirementInspectionResult',
    'FactSet',
    'FactValue',
    'ImpactDispositionSubmission',
    'InspectCall',
    'InspectableHandle',
    'NavigationHandle',
    'NavigationId',
    'NavigationInspectionResult',
    'NonEmptyString',
    'ObligationId',
    'PendingResult',
    'PolicyHandle',
    'PolicyInspectionResult',
    'PrepareCall',
    'ProvideFactSubmission',
    'QueryCall',
    'QueryRequest',
    'QueryResult',
    'ReadRequest',
    'ReadResult',
    'RejectedResult',
    'RelatedRequest',
    'RelatedResult',
    'RelationshipHandle',
    'RelationshipInspectionResult',
    'ResolveCall',
    'ReviewScope',
    'RouteRequest',
    'RouteResult',
    'SemanticProposal',
    'SnapshotHandle',
    'SnapshotId',
    'SnapshotInspectionResult',
    'StructuredScope',
    'Submission',
    'WholeArtifactScope',
    'decode_contract',
)
