# Generated by tools/standards_engine/contracts/generate_contract.py.
# Do not edit this file directly.
from __future__ import annotations

from dataclasses import dataclass
from types import MappingProxyType
from typing import Any, Mapping, TypeAlias

INTERFACE_SCHEMA_VERSION = 9
PUBLIC_OPERATIONS = MappingProxyType(
{'inspect': {'capability': 'standards.read',
             'input': 'InspectCall',
             'results': ['InspectionResult', 'RejectedResult']},
 'prepare': {'capability': 'standards.analyze',
             'input': 'PrepareCall',
             'results': ['PendingResult', 'CompleteResult', 'RejectedResult']},
 'query': {'capability': 'standards.read',
           'input': 'QueryCall',
           'results': ['NavigationResult', 'RejectedResult']},
 'resolve': {'capability_by_submission': {'consumer-disposition': 'standards.review.consumer',
                                          'coverage-attestation': 'standards.review.audit',
                                          'impact-disposition': 'standards.review.impact',
                                          'provide-fact': 'standards.analyze'},
             'input': 'ResolveCall',
             'results': ['PendingResult', 'CompleteResult', 'RejectedResult']}}
)
REQUEST_FIELDS = MappingProxyType(
{'AnalysisRequest': {'properties': ['base_snapshot',
                                    'changes',
                                    'contract_version',
                                    'kind',
                                    'prior_analysis',
                                    'proposed_snapshot',
                                    'semantic_proposals'],
                     'required': ['kind',
                                  'base_snapshot',
                                  'proposed_snapshot',
                                  'changes',
                                  'semantic_proposals',
                                  'contract_version']},
 'InspectCall': {'properties': ['handle'], 'required': ['handle']},
 'PrepareCall': {'properties': ['request'], 'required': ['request']},
 'QueryCall': {'properties': ['request', 'snapshot'],
               'required': ['snapshot', 'request']},
 'ReadRequest': {'properties': ['kind', 'target'], 'required': ['kind', 'target']},
 'RelatedRequest': {'properties': ['direction',
                                   'groups',
                                   'kind',
                                   'target',
                                   'transitive'],
                    'required': ['kind',
                                 'target',
                                 'groups',
                                 'direction',
                                 'transitive']},
 'ResolveCall': {'properties': ['analysis', 'submission'],
                 'required': ['analysis', 'submission']},
 'RouteRequest': {'properties': ['facts', 'kind'], 'required': ['kind', 'facts']}}
)
RESULT_KIND_TO_DEFINITION = MappingProxyType(
{'analysis-context-inspection-result': 'AnalysisContextInspectionResult',
 'analysis-state': 'AnalysisState',
 'certificate-inspection-result': 'CertificateInspectionResult',
 'complete-result': 'CompleteResult',
 'coverage-attestation-inspection-result': 'CoverageAttestationInspectionResult',
 'coverage-authority-view-inspection-result': 'CoverageAuthorityViewInspectionResult',
 'coverage-requirement-inspection-result': 'CoverageRequirementInspectionResult',
 'fact-observation-inspection-result': 'FactObservationInspectionResult',
 'fact-requirement-inspection-result': 'FactRequirementInspectionResult',
 'navigation-inspection-result': 'NavigationInspectionResult',
 'pending-result': 'PendingResult',
 'policy-inspection-result': 'PolicyInspectionResult',
 'read-result': 'ReadResult',
 'rejected-result': 'RejectedResult',
 'related-result': 'RelatedResult',
 'relationship-inspection-result': 'RelationshipInspectionResult',
 'route-result': 'RouteResult',
 'snapshot-inspection-result': 'SnapshotInspectionResult'}
)
INSPECTABLE_HANDLE_DEFINITIONS = ('SnapshotHandle', 'NavigationHandle', 'AnalysisHandle', 'PolicyHandle', 'RelationshipHandle', 'CertificateHandle', 'CoverageAuthorityViewHandle', 'CoverageRequirementHandle', 'CoverageAttestationHandle', 'AnalysisContextHandle', 'FactRequirementHandle', 'FactObservationHandle')


def _freeze(value: Any) -> Any:
    if isinstance(value, Mapping):
        return MappingProxyType(
            {str(key): _freeze(item) for key, item in value.items()}
        )
    if isinstance(value, (list, tuple)):
        return tuple(_freeze(item) for item in value)
    return value


def _thaw(value: Any) -> Any:
    if isinstance(value, Mapping):
        return {key: _thaw(item) for key, item in value.items()}
    if isinstance(value, tuple):
        return [_thaw(item) for item in value]
    return value


@dataclass(frozen=True, slots=True)
class ReadRequest:
    target: str
    kind: str = 'read'


@dataclass(frozen=True, slots=True)
class RouteRequest:
    facts: Mapping[str, object]
    kind: str = 'route'

    def __post_init__(self) -> None:
        object.__setattr__(self, 'facts', _freeze(self.facts))


@dataclass(frozen=True, slots=True)
class RelatedRequest:
    target: str
    groups: tuple[str, ...]
    direction: str
    transitive: bool = False
    kind: str = 'related'


QueryRequest: TypeAlias = RouteRequest | ReadRequest | RelatedRequest


@dataclass(frozen=True, slots=True)
class QueryCall:
    snapshot: Mapping[str, object]
    request: QueryRequest

    def __post_init__(self) -> None:
        object.__setattr__(self, 'snapshot', _freeze(self.snapshot))


@dataclass(frozen=True, slots=True)
class InspectCall:
    handle: Mapping[str, object]

    def __post_init__(self) -> None:
        object.__setattr__(self, 'handle', _freeze(self.handle))


@dataclass(frozen=True, slots=True)
class AnalysisRequest:
    base_snapshot: Mapping[str, object]
    proposed_snapshot: Mapping[str, object]
    changes: tuple[object, ...]
    semantic_proposals: tuple[object, ...]
    prior_analysis: Mapping[str, object] | None = None
    contract_version: int = 2
    kind: str = 'analysis-request'

    def __post_init__(self) -> None:
        object.__setattr__(self, 'base_snapshot', _freeze(self.base_snapshot))
        object.__setattr__(self, 'proposed_snapshot', _freeze(self.proposed_snapshot))
        if self.prior_analysis is not None:
            object.__setattr__(self, 'prior_analysis', _freeze(self.prior_analysis))


@dataclass(frozen=True, slots=True)
class PrepareCall:
    request: AnalysisRequest


@dataclass(frozen=True, slots=True)
class ResolveCall:
    analysis: Mapping[str, object]
    submission: object


@dataclass(frozen=True, slots=True)
class ContractResult:
    _value: Mapping[str, object]

    @classmethod
    def from_value(cls, value: dict[str, object]):
        return cls(_freeze(value))

    @property
    def kind(self) -> str:
        return str(self._value['kind'])

    def as_contract(self) -> dict[str, object]:
        return _thaw(self._value)


class RouteResult(ContractResult):
    pass

class ReadResult(ContractResult):
    pass

class RelatedResult(ContractResult):
    pass

class PendingResult(ContractResult):
    pass

class CompleteResult(ContractResult):
    pass

class RejectedResult(ContractResult):
    pass

class SnapshotInspectionResult(ContractResult):
    pass

class PolicyInspectionResult(ContractResult):
    pass

class RelationshipInspectionResult(ContractResult):
    pass

class NavigationInspectionResult(ContractResult):
    pass

class CertificateInspectionResult(ContractResult):
    pass

class CoverageAuthorityViewInspectionResult(ContractResult):
    pass

class CoverageRequirementInspectionResult(ContractResult):
    pass

class CoverageAttestationInspectionResult(ContractResult):
    pass

class AnalysisContextInspectionResult(ContractResult):
    pass

class FactRequirementInspectionResult(ContractResult):
    pass

class FactObservationInspectionResult(ContractResult):
    pass


QueryResult: TypeAlias = RouteResult | ReadResult | RelatedResult | RejectedResult
ContractInspectionResult: TypeAlias = SnapshotInspectionResult | PolicyInspectionResult | RelationshipInspectionResult | NavigationInspectionResult | CertificateInspectionResult | CoverageAuthorityViewInspectionResult | CoverageRequirementInspectionResult | CoverageAttestationInspectionResult | AnalysisContextInspectionResult | FactRequirementInspectionResult | FactObservationInspectionResult | RejectedResult
