"""Neutral canonical standards metadata loading and structural validation."""

from .errors import MetadataError, MetadataFailure
from .corpus import load_canonical_standards_corpus
from .loader import (
    CANONICAL_MODULE_CORPUS,
    load_canonical_module_corpus,
    load_module_metadata,
    validate_module_metadata,
)
from .model import (
    CanonicalModuleCorpus,
    CanonicalStandardsCorpus,
    MetadataValidation,
    ModuleMetadata,
)
from .policy_units import (
    POLICY_UNIT_REGISTRY,
    PolicyUnit,
    PolicyUnitCorpus,
    PolicyUnitTombstone,
    UnmappedModuleProjection,
    load_policy_unit_corpus,
    markdown_structural_digest,
    project_unmapped_module,
)
from .source import (
    ContentSource,
    ContentSourceInput,
    DirectoryContentSource,
    FrozenContentSource,
    RecordingContentSource,
    content_source,
)
from .suite_inputs import (
    SUITE_INPUT_CONTRACT,
    SUITE_INPUT_SCHEMA_VERSION,
    RepositoryIndexObservation,
    SuiteDefinitionInput,
    SuiteDependencyProjection,
    SuiteFileInput,
    SuiteInputManifest,
    SuiteInputUse,
    file_digest,
    load_suite_input_manifest,
    suite_input_manifest_bytes,
)
__all__ = (
    "CANONICAL_MODULE_CORPUS",
    "POLICY_UNIT_REGISTRY",
    "CanonicalModuleCorpus",
    "CanonicalStandardsCorpus",
    "ContentSource",
    "ContentSourceInput",
    "DirectoryContentSource",
    "FrozenContentSource",
    "MetadataError",
    "MetadataFailure",
    "MetadataValidation",
    "ModuleMetadata",
    "PolicyUnit",
    "PolicyUnitCorpus",
    "PolicyUnitTombstone",
    "RecordingContentSource",
    "RepositoryIndexObservation",
    "SUITE_INPUT_CONTRACT",
    "SUITE_INPUT_SCHEMA_VERSION",
    "SuiteDefinitionInput",
    "SuiteDependencyProjection",
    "SuiteFileInput",
    "SuiteInputManifest",
    "SuiteInputUse",
    "UnmappedModuleProjection",
    "load_canonical_standards_corpus",
    "load_canonical_module_corpus",
    "load_policy_unit_corpus",
    "load_module_metadata",
    "markdown_structural_digest",
    "project_unmapped_module",
    "validate_module_metadata",
    "content_source",
    "file_digest",
    "load_suite_input_manifest",
    "suite_input_manifest_bytes",
)
