from __future__ import annotations

import argparse
import json
import pprint
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[3]
SCHEMA_PATH = REPO_ROOT / "tools/standards_engine/contracts/a1-contract.schema.json"
PYTHON_PATH = (
    REPO_ROOT / "tools/standards_engine/standards_engine/_generated_contract.py"
)
TOOLS_PATH = REPO_ROOT / "tools/standards_engine/contracts/generated/agent-tools.json"

REQUEST_DEFINITIONS = (
    "RouteRequest",
    "ReadRequest",
    "RelatedRequest",
    "QueryCall",
    "AnalysisRequest",
    "PrepareCall",
    "ResolveCall",
    "InspectCall",
)
RESULT_UNIONS = (
    "NavigationResult",
    "InspectionResult",
)


def _load_schema() -> dict[str, Any]:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def _refs(schema: dict[str, Any], definition: str) -> tuple[str, ...]:
    node = schema["$defs"][definition]
    return tuple(item["$ref"].rsplit("/", 1)[1] for item in node.get("oneOf", ()))


def _result_definitions(schema: dict[str, Any]) -> tuple[tuple[str, str], ...]:
    selected = []
    for name, node in schema["$defs"].items():
        kind = node.get("properties", {}).get("kind", {}).get("const")
        if isinstance(kind, str) and (
            kind.endswith("-result") or kind == "analysis-state"
        ):
            selected.append((name, kind))
    return tuple(selected)


def _request_fields(schema: dict[str, Any]) -> dict[str, dict[str, object]]:
    return {
        name: {
            "required": schema["$defs"][name].get("required", []),
            "properties": sorted(schema["$defs"][name].get("properties", {})),
        }
        for name in REQUEST_DEFINITIONS
    }


def _python_projection(schema: dict[str, Any]) -> str:
    metadata = schema["x-standards-engine-contract"]
    results = _result_definitions(schema)
    wrappers = tuple((name, kind) for name, kind in results if kind != "analysis-state")
    result_map = {kind: name for name, kind in results}
    request_fields = _request_fields(schema)
    inspectable = tuple(_refs(schema, "InspectableHandle"))
    public_operations = metadata["public_operations"]

    lines = [
        "# Generated by tools/standards_engine/contracts/generate_contract.py.",
        "# Do not edit this file directly.",
        "from __future__ import annotations",
        "",
        "from dataclasses import dataclass",
        "from types import MappingProxyType",
        "from typing import Any, Mapping, TypeAlias",
        "",
        f"INTERFACE_SCHEMA_VERSION = {metadata['schema_version']}",
        "PUBLIC_OPERATIONS = MappingProxyType(",
        pprint.pformat(public_operations, sort_dicts=True, width=88),
        ")",
        "REQUEST_FIELDS = MappingProxyType(",
        pprint.pformat(request_fields, sort_dicts=True, width=88),
        ")",
        "RESULT_KIND_TO_DEFINITION = MappingProxyType(",
        pprint.pformat(result_map, sort_dicts=True, width=88),
        ")",
        f"INSPECTABLE_HANDLE_DEFINITIONS = {inspectable!r}",
        "",
        "",
        "def _freeze(value: Any) -> Any:",
        "    if isinstance(value, Mapping):",
        "        return MappingProxyType(",
        "            {str(key): _freeze(item) for key, item in value.items()}",
        "        )",
        "    if isinstance(value, (list, tuple)):",
        "        return tuple(_freeze(item) for item in value)",
        "    return value",
        "",
        "",
        "def _thaw(value: Any) -> Any:",
        "    if isinstance(value, Mapping):",
        "        return {key: _thaw(item) for key, item in value.items()}",
        "    if isinstance(value, tuple):",
        "        return [_thaw(item) for item in value]",
        "    return value",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class ReadRequest:",
        "    target: str",
        "    kind: str = 'read'",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class RouteRequest:",
        "    facts: Mapping[str, object]",
        "    kind: str = 'route'",
        "",
        "    def __post_init__(self) -> None:",
        "        object.__setattr__(self, 'facts', _freeze(self.facts))",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class RelatedRequest:",
        "    target: str",
        "    groups: tuple[str, ...]",
        "    direction: str",
        "    transitive: bool = False",
        "    kind: str = 'related'",
        "",
        "",
        "QueryRequest: TypeAlias = RouteRequest | ReadRequest | RelatedRequest",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class QueryCall:",
        "    snapshot: Mapping[str, object]",
        "    request: QueryRequest",
        "",
        "    def __post_init__(self) -> None:",
        "        object.__setattr__(self, 'snapshot', _freeze(self.snapshot))",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class InspectCall:",
        "    handle: Mapping[str, object]",
        "",
        "    def __post_init__(self) -> None:",
        "        object.__setattr__(self, 'handle', _freeze(self.handle))",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class AnalysisRequest:",
        "    base_snapshot: Mapping[str, object]",
        "    proposed_snapshot: Mapping[str, object]",
        "    changes: tuple[object, ...]",
        "    semantic_proposals: tuple[object, ...]",
        "    prior_analysis: Mapping[str, object] | None = None",
        "    contract_version: int = 2",
        "    kind: str = 'analysis-request'",
        "",
        "    def __post_init__(self) -> None:",
        "        object.__setattr__(self, 'base_snapshot', _freeze(self.base_snapshot))",
        "        object.__setattr__(self, 'proposed_snapshot', _freeze(self.proposed_snapshot))",
        "        if self.prior_analysis is not None:",
        "            object.__setattr__(self, 'prior_analysis', _freeze(self.prior_analysis))",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class PrepareCall:",
        "    request: AnalysisRequest",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class ResolveCall:",
        "    analysis: Mapping[str, object]",
        "    submission: object",
        "",
        "",
        "@dataclass(frozen=True, slots=True)",
        "class ContractResult:",
        "    _value: Mapping[str, object]",
        "",
        "    @classmethod",
        "    def from_value(cls, value: dict[str, object]):",
        "        return cls(_freeze(value))",
        "",
        "    @property",
        "    def kind(self) -> str:",
        "        return str(self._value['kind'])",
        "",
        "    def as_contract(self) -> dict[str, object]:",
        "        return _thaw(self._value)",
        "",
    ]
    for name, _kind in wrappers:
        lines.extend(("", f"class {name}(ContractResult):", "    pass"))
    navigation = " | ".join(_refs(schema, "NavigationResult") + ("RejectedResult",))
    inspections = " | ".join(
        name for name in _refs(schema, "InspectionResult") if name != "AnalysisState"
    )
    lines.extend(
        (
            "",
            "",
            f"QueryResult: TypeAlias = {navigation}",
            f"ContractInspectionResult: TypeAlias = {inspections} | RejectedResult",
            "",
        )
    )
    return "\n".join(lines)


def _agent_tools_projection(schema: dict[str, Any]) -> str:
    metadata = schema["x-standards-engine-contract"]
    descriptions = {
        "query": "Route, read, or navigate relationships in one exact standards snapshot.",
        "prepare": "Prepare immutable read-only analysis for exact base and proposed snapshots.",
        "resolve": "Advance one immutable analysis with an authorized typed submission.",
        "inspect": "Inspect an exact Standards Engine handle and its provenance.",
    }
    tools = []
    for operation, contract in metadata["public_operations"].items():
        tools.append(
            {
                "name": f"standards_{operation}",
                "description": descriptions[operation],
                "input_definition": contract["input"],
                "input_schema": {"$ref": f"#/$defs/{contract['input']}"},
                "result_definitions": contract["results"],
            }
        )
    value = {
        "schema_version": metadata["schema_version"],
        "canonical_schema": "../a1-contract.schema.json",
        "tools": tools,
        "$defs": schema["$defs"],
    }
    return json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"


def render_projections() -> dict[Path, str]:
    schema = _load_schema()
    return {
        PYTHON_PATH: _python_projection(schema),
        TOOLS_PATH: _agent_tools_projection(schema),
    }


def check_projections() -> tuple[str, ...]:
    stale = []
    for path, expected in render_projections().items():
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(path.relative_to(REPO_ROOT).as_posix())
    return tuple(stale)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Standards Engine projections"
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    projections = render_projections()
    if args.check:
        stale = check_projections()
        if stale:
            print(
                "stale generated contract projections: " + ", ".join(stale),
                file=sys.stderr,
            )
            return 1
        return 0
    for path, content in projections.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
